/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oorestaurants;
import java.awt.Component;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
/**
 *
 * @author MANAN SHAH
 */
public class oo_restaurants extends javax.swing.JFrame {

    /**
     * Creates new form oo_restaurants
     */
    public oo_restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtontotal = new javax.swing.JButton();
        jButtonreceipt = new javax.swing.JButton();
        jButtonreset = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        totaltvtext = new javax.swing.JTextField();
        totalmobtext = new javax.swing.JTextField();
        totalprotext = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        sonyttext = new javax.swing.JTextField();
        MIttext = new javax.swing.JTextField();
        oneplusttext = new javax.swing.JTextField();
        haierttext = new javax.swing.JTextField();
        philipsttext = new javax.swing.JTextField();
        lgttext = new javax.swing.JTextField();
        samsungttext = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        apple11mob = new javax.swing.JTextField();
        oneplusmob = new javax.swing.JTextField();
        samsungno10mob = new javax.swing.JTextField();
        realmemob = new javax.swing.JTextField();
        samsungno20mob = new javax.swing.JTextField();
        samsunggalmob = new javax.swing.JTextField();
        apple10mob = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        Taxtext = new javax.swing.JTextField();
        totaltext = new javax.swing.JTextField();
        Subtotaltext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jblTotal = new javax.swing.JLabel();
        jblSubTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jButtontotal.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtontotal.setText("Total");
        jButtontotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontotalActionPerformed(evt);
            }
        });

        jButtonreceipt.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtonreceipt.setText("Receipt");
        jButtonreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonreceiptActionPerformed(evt);
            }
        });

        jButtonreset.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtonreset.setText("Reset");
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });

        jButtonexit.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtonexit.setText("Exit");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButtontotal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButtonreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButtonreset, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButtonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtontotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonreceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 940, 80));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 66)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Electronic shop managment System");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\logo file for project\\3.jpeg")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 3));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\logo file for project\\stote logo.jpg")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 3));

        jLabel28.setIcon(new javax.swing.ImageIcon("E:\\logo file for project\\3.jpeg")); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addGap(351, 351, 351)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 140));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TOTAL OF T.V.");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("TOTAL OF PRODUCTS");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("TOTAL OF MOBILES");

        totaltvtext.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        totaltvtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totaltvtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltvtextActionPerformed(evt);
            }
        });

        totalmobtext.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        totalmobtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalmobtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalmobtextActionPerformed(evt);
            }
        });

        totalprotext.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        totalprotext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalprotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalprotextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalprotext, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totaltvtext))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalmobtext)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totaltvtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalmobtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalprotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 460, 210));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 420, 640));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("T.V.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("T.V. NAME");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("QUANTITY");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("SONY BRAVIA (55 inches) 4K");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("MI TV (50 inches) 4K ULTRA");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("ONEPLUS Q1(55 inches) 4K");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Haier FULL HD LED(43 inches)");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("PHILIPS 6600 4K UHD(58 inches)");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("LG (55 inches) 4K UHD LED TV");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("SAMSUNG (65 inches) 4K ULTRA HD");
        jLabel25.setToolTipText("");

        sonyttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sonyttext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sonyttext.setText("0");
        sonyttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonyttextActionPerformed(evt);
            }
        });

        MIttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MIttext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MIttext.setText("0");
        MIttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIttextActionPerformed(evt);
            }
        });

        oneplusttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oneplusttext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oneplusttext.setText("0");
        oneplusttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneplusttextActionPerformed(evt);
            }
        });

        haierttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        haierttext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        haierttext.setText("0");
        haierttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haierttextActionPerformed(evt);
            }
        });

        philipsttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        philipsttext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        philipsttext.setText("0");
        philipsttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philipsttextActionPerformed(evt);
            }
        });

        lgttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lgttext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lgttext.setText("0");
        lgttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgttextActionPerformed(evt);
            }
        });

        samsungttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        samsungttext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        samsungttext.setText("0");
        samsungttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samsungttextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(123, 123, 123)
                .addComponent(jLabel6)
                .addGap(18, 18, 18))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MIttext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sonyttext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneplusttext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haierttext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(philipsttext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgttext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(samsungttext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(sonyttext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(MIttext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(oneplusttext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(haierttext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(philipsttext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lgttext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(samsungttext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 460, 330));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MOBILES");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MOBILES NAME");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("QUANTITY");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("APPLE IPHONE 11 PRO MAX");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ONEPLUS 7T PRO");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SAMSUNG GALAXY NOTE 10 PLUS");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("REALME X");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SAMSUNG GALAXY NOTE 20 ULTRA ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("SAMSUNG GALAXY S20 ULTRA");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("APPLE IPHONE XS MAX");

        apple11mob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apple11mob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apple11mob.setText("0");
        apple11mob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple11mobActionPerformed(evt);
            }
        });

        oneplusmob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oneplusmob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oneplusmob.setText("0");
        oneplusmob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneplusmobActionPerformed(evt);
            }
        });

        samsungno10mob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        samsungno10mob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        samsungno10mob.setText("0");
        samsungno10mob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samsungno10mobActionPerformed(evt);
            }
        });

        realmemob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        realmemob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        realmemob.setText("0");
        realmemob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realmemobActionPerformed(evt);
            }
        });

        samsungno20mob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        samsungno20mob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        samsungno20mob.setText("0");
        samsungno20mob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samsungno20mobActionPerformed(evt);
            }
        });

        samsunggalmob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        samsunggalmob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        samsunggalmob.setText("0");
        samsunggalmob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samsunggalmobActionPerformed(evt);
            }
        });

        apple10mob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apple10mob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apple10mob.setText("0");
        apple10mob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple10mobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(159, 159, 159))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(realmemob)
                            .addComponent(samsungno20mob)
                            .addComponent(apple11mob)
                            .addComponent(oneplusmob)
                            .addComponent(samsungno10mob)
                            .addComponent(samsunggalmob)
                            .addComponent(apple10mob))
                        .addGap(16, 16, 16))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(apple11mob, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(oneplusmob, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(samsungno10mob, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(realmemob, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(samsungno20mob, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(samsunggalmob, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apple10mob, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 460, 330));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        Taxtext.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Taxtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Taxtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaxtextActionPerformed(evt);
            }
        });

        totaltext.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        totaltext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totaltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltextActionPerformed(evt);
            }
        });

        Subtotaltext.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Subtotaltext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Subtotaltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtotaltextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tax");

        jblTotal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTotal.setText("Total");

        jblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblSubTotal.setText("SubTotal");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jblSubTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Subtotaltext, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Taxtext, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totaltext, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Taxtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Subtotaltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 460, 210));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtontotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontotalActionPerformed
        SubClass_child Itemcost = new SubClass_child();
        
        //double iTax, isubtoal,itotal;
        
        Itemcost.sony = Itemcost.psony * Double.parseDouble(sonyttext.getText());
        Itemcost.MI = Itemcost.pMI * Double.parseDouble(MIttext.getText());
        Itemcost.oneplus = Itemcost.poneplus * Double.parseDouble(oneplusttext.getText());
        Itemcost.haier = Itemcost.phaier * Double.parseDouble(haierttext.getText());
        Itemcost.philips = Itemcost.pphilips * Double.parseDouble(philipsttext.getText());
        Itemcost.LG = Itemcost.pLG * Double.parseDouble(lgttext.getText());
        Itemcost.samsung = Itemcost.psamsung * Double.parseDouble(samsungttext.getText());
        
        Itemcost.apple11pro = Itemcost.papple11pro * Double.parseDouble(apple11mob.getText());
        Itemcost.oneplus7 = Itemcost.poneplus7 * Double.parseDouble(oneplusmob.getText());
        Itemcost.samsungnote10 = Itemcost.psamsungnote10 * Double.parseDouble(samsungno10mob.getText());
        Itemcost.realme = Itemcost.prealme * Double.parseDouble(realmemob.getText());
        Itemcost.samsungnote20 = Itemcost.psamsungnote20 * Double.parseDouble(samsungno20mob.getText());
        Itemcost.samsungS20 = Itemcost.psamsungS20 * Double.parseDouble(samsunggalmob.getText());
        Itemcost.appleXS = Itemcost.pappleXS * Double.parseDouble(apple10mob.getText());
        
        double isubtotal = Itemcost.GetAmount();
        double iTax = Itemcost.cFindtax(isubtotal);
        double itotal = isubtotal + iTax;
        
        String Subtotal = String.format("$%.2f",isubtotal);
        
        Subtotaltext.setText(Subtotal);
        
        String Tax = String.format("$%.2f",iTax);
        
        Taxtext.setText(Tax);
        
        String total = String.format("$%.2f",itotal);
        
        totaltext.setText(total);
        
        //========================================================================
        String totaltv = String.format("$%.2f",Itemcost.Tv);
        totaltvtext.setText(totaltv);
        
        String totalmob = String.format("$%.2f",Itemcost.mobiles);
        totalmobtext.setText(totalmob);
        
        String totalpro = String.format("$%.2f",Itemcost.totaloftm);
        totalprotext.setText(totalpro);
    }//GEN-LAST:event_jButtontotalActionPerformed

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        for(Component c:jPanel4.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                JTextField cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        //========================================================================
        for(Component c:jPanel6.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                JTextField cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        
        //=========================================================================
        
        for(Component c:jPanel3.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                JTextField cleartext = (JTextField)c;
                cleartext.setText("");
            }
        }
        //========================================================================
        for(Component c:jPanel7.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                JTextField cleartext = (JTextField)c;
                cleartext.setText("");
            }
        }
        
        //=======================================================================
        
        jtxtReceipt.setText(null);
    }//GEN-LAST:event_jButtonresetActionPerformed

    private void TaxtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaxtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaxtextActionPerformed

    private void totaltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltextActionPerformed

    private void SubtotaltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtotaltextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubtotaltextActionPerformed

    private void apple11mobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple11mobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apple11mobActionPerformed

    private void oneplusmobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneplusmobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneplusmobActionPerformed

    private void samsungno10mobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samsungno10mobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samsungno10mobActionPerformed

    private void realmemobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realmemobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realmemobActionPerformed

    private void samsungno20mobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samsungno20mobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samsungno20mobActionPerformed

    private void samsunggalmobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samsunggalmobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samsunggalmobActionPerformed

    private void apple10mobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple10mobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apple10mobActionPerformed

    private void sonyttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonyttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sonyttextActionPerformed

    private void MIttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIttextActionPerformed

    private void oneplusttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneplusttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneplusttextActionPerformed

    private void haierttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haierttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haierttextActionPerformed

    private void philipsttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philipsttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_philipsttextActionPerformed

    private void lgttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgttextActionPerformed

    private void samsungttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samsungttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samsungttextActionPerformed

    private void totaltvtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltvtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltvtextActionPerformed

    private void totalmobtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalmobtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalmobtextActionPerformed

    private void totalprotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalprotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalprotextActionPerformed

    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
            SubClass_child iExit = new SubClass_child();
            iExit.iExitSystem();
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jButtonreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonreceiptActionPerformed
        
        int refs = 1325 + (int) (Math.random()*4238);
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());
        
                jtxtReceipt.append("     Electronic store Managment System: \n" + 
                        "Reference:\t\t\t" + refs +
                        "\n============================================\n" + 
                        "T.V.:\t\t\t\t" + totaltvtext.getText() + "\n\n" + 
                        "MOBILES:\t\t\t" + totalmobtext.getText() + "\n\n" + 
                        "TOTAL OF PRODUCT:\t\t" + totalprotext.getText() + "\n\n" +
                        "\n============================================\n" + "\n\n" + 
                        "TAX:\t\t\t\t" + Taxtext.getText() + "\n\n" +
                        "SUBTOTAL:\t\t\t" + Subtotaltext.getText() + "\n\n" +
                        "TOTAL:\t\t\t\t" + totaltext.getText() + "\n" + 
                        "\n============================================\n" +
                        "\nDATE: " + Tdate.format(timer.getTime()) +
                        "\tTIME: " + tTime.format(timer.getTime()) +
                        "\n\n\t\tTHANK YOU \n\n");
    }//GEN-LAST:event_jButtonreceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, IllegalAccessException, InstantiationException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oo_restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oo_restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oo_restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oo_restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oo_restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MIttext;
    private javax.swing.JTextField Subtotaltext;
    private javax.swing.JTextField Taxtext;
    private javax.swing.JTextField apple10mob;
    private javax.swing.JTextField apple11mob;
    private javax.swing.JTextField haierttext;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JButton jButtonreceipt;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JButton jButtontotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblSubTotal;
    private javax.swing.JLabel jblTotal;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField lgttext;
    private javax.swing.JTextField oneplusmob;
    private javax.swing.JTextField oneplusttext;
    private javax.swing.JTextField philipsttext;
    private javax.swing.JTextField realmemob;
    private javax.swing.JTextField samsunggalmob;
    private javax.swing.JTextField samsungno10mob;
    private javax.swing.JTextField samsungno20mob;
    private javax.swing.JTextField samsungttext;
    private javax.swing.JTextField sonyttext;
    private javax.swing.JTextField totalmobtext;
    private javax.swing.JTextField totalprotext;
    private javax.swing.JTextField totaltext;
    private javax.swing.JTextField totaltvtext;
    // End of variables declaration//GEN-END:variables
}
